# 🧮 Bộ đề luyện NumPy cho Khoa học dữ liệu / AI–ML

Bộ đề gồm **38 bài** chia theo 8 nhóm chủ đề, sắp theo độ khó tăng dần.
Mỗi bài có **1 ô đề bài** và **1 ô code trống** để bạn tự giải.

**Cách dùng:** đọc đề, tự code trong ô trống, rồi `print` kết quả và đối chiếu với *Expected output*. Quy ước chung: `import numpy as np`, các hàm `std`/`var` dùng `ddof=0` (mặc định của NumPy).

| Nhóm | Chủ đề | Bài |
|---|---|---|
| A | Tạo mảng & Indexing | 1–6 |
| B | Aggregation theo trục | 7–11 |
| C | Reshape · Broadcasting · Vectorization | 12–16 |
| D | Đại số tuyến tính / Ma trận | 17–21 |
| E | Metrics phân loại (classification) | 22–28 |
| F | Metrics hồi quy (regression) | 29–31 |
| G | Preprocessing | 32–35 |
| H | Distance & Similarity | 36–38 |

In [1]:
import numpy as np

## 🟦 Nhóm A — Tạo mảng & Indexing

### Bài 1 — Tạo các mảng cơ bản

**Yêu cầu:** Tạo và in ra các mảng sau bằng các hàm khởi tạo của NumPy:
- `a`: dãy số nguyên từ 0 đến 9 (dùng `np.arange`).
- `b`: 5 giá trị cách đều từ 0 đến 1 (dùng `np.linspace`).
- `I`: ma trận đơn vị 3×3 (dùng `np.eye`).
- `M`: các số 1..12 xếp thành ma trận 3×4 (dùng `np.arange` + `reshape`).

**Input mẫu:**
```python
# không có input, tự tạo theo yêu cầu
```

**Expected output:**
```
a = [0 1 2 3 4 5 6 7 8 9]
b = [0.   0.25 0.5  0.75 1.  ]
I =
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
M =
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
```

In [2]:
a = np.arange(0, 10)
b = np.linspace(0, 1, 5)
I = np.eye(3)
M = np.arange(1, 13); M = M.reshape(3,4)
a, b, I, M

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0.  , 0.25, 0.5 , 0.75, 1.  ]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]))

### Bài 2 — Indexing & slicing trên ma trận 2D

**Yêu cầu:** Cho ma trận `M`. Hãy lấy ra (theo thứ tự):
1. Hàng thứ 2 (chỉ số 1).
2. Cột cuối cùng.
3. Phần tử ở hàng 2 (chỉ số 2), cột 3 (chỉ số 3).
4. Hàng đầu tiên theo thứ tự đảo ngược.
5. Khối con 2×2 ở góc trên–trái.

**Input mẫu:**
```python
M = np.arange(1, 13).reshape(3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
```

**Expected output:**
```
1) M[1]        -> [5 6 7 8]
2) M[:, -1]    -> [ 4  8 12]
3) M[2, 3]     -> 12
4) M[0, ::-1]  -> [4 3 2 1]
5) M[:2, :2]   ->
[[1 2]
 [5 6]]
```

In [3]:
M = np.arange(1, 13).reshape(3, 4)
M[1]
M[:,-1]
M[2,3]
M[1::-1]
M[:2, :2]

array([[1, 2],
       [5, 6]])

### Bài 3 — Boolean masking (lọc theo điều kiện)

**Yêu cầu:** Cho mảng `a`. Hãy tính:
1. Mảng các phần tử **lớn hơn 5**.
2. **Số lượng** phần tử chẵn.
3. **Tổng** các phần tử lớn hơn 5.

**Input mẫu:**
```python
a = np.array([3, 8, 1, 9, 4, 7, 2, 6])
```

**Expected output:**
```
1) a[a > 5]        -> [8 9 7 6]
2) (a % 2 == 0).sum() -> 4
3) a[a > 5].sum()  -> 30
```

In [4]:
a = np.array([3, 8, 1, 9, 4, 7, 2, 6])
a[a > 5]
np.size(a[a % 2 == 0])
np.sum(a[a > 5])

np.int64(30)

### Bài 4 — Fancy indexing & gán theo mask

**Yêu cầu:** Cho mảng `a`. Hãy:
1. Lấy các phần tử ở chỉ số `[0, 2, 4]`.
2. Gán giá trị 0 cho mọi phần tử **nhỏ hơn 25** (sửa tại chỗ), rồi in `a`.

**Input mẫu:**
```python
a = np.array([10, 20, 30, 40, 50])
```

**Expected output:**
```
1) a[[0, 2, 4]]    -> [10 30 50]
2) a sau khi gán   -> [ 0  0 30 40 50]
```

In [5]:
a = np.array([10, 20, 30, 40, 50])
a[[0,2,4]]
a[a < 25] = 0
a

array([ 0,  0, 30, 40, 50])

### Bài 5 — np.where & np.clip

**Yêu cầu:** Cho mảng `a`. Hãy:
1. Dùng `np.where` thay mọi giá trị âm bằng 0 (giống ReLU).
2. Dùng `np.clip` để giới hạn giá trị trong đoạn `[0, 5]`.

**Input mẫu:**
```python
a = np.array([-2, 3, -1, 5, 0, -4, 8])
```

**Expected output:**
```
1) np.where(a < 0, 0, a) -> [0 3 0 5 0 0 8]
2) np.clip(a, 0, 5)      -> [0 3 0 5 0 0 5]
```

In [6]:
a = np.array([-2, 3, -1, 5, 0, -4, 8])
np.where(a < 0, 0, a)
np.clip(a, 0, 5)

array([0, 3, 0, 5, 0, 0, 5])

### Bài 6 — np.unique & np.bincount (đếm tần suất nhãn)

**Yêu cầu:** Cho mảng nhãn `labels`. Hãy:
1. Lấy các nhãn duy nhất kèm số lần xuất hiện (dùng `np.unique(..., return_counts=True)`).
2. Đếm số lần xuất hiện mỗi nhãn bằng `np.bincount`.

**Input mẫu:**
```python
labels = np.array([0, 1, 2, 1, 0, 1, 2, 2, 2, 0])
```

**Expected output:**
```
1) values -> [0 1 2] ; counts -> [3 3 4]
2) np.bincount(labels) -> [3 3 4]
```

In [7]:
labels = np.array([0, 1, 2, 1, 0, 1, 2, 2, 2, 0])
np.unique(labels, return_counts=True)
np.bincount(labels)

array([3, 3, 4])

## 🟩 Nhóm B — Aggregation theo trục (axis)

### Bài 7 — sum · prod · cumsum

**Yêu cầu:** Cho ma trận `M` và vector `v`. Hãy tính:
1. Tổng toàn bộ phần tử của `M`.
2. Tổng theo từng **cột** (`axis=0`).
3. Tổng theo từng **hàng** (`axis=1`).
4. Tích theo từng **hàng**.
5. Tổng tích lũy (`cumsum`) của `v`.

**Input mẫu:**
```python
M = np.array([[1, 2, 3],
              [4, 5, 6]])
v = np.array([1, 2, 3, 4])
```

**Expected output:**
```
1) M.sum()         -> 21
2) M.sum(axis=0)   -> [5 7 9]
3) M.sum(axis=1)   -> [ 6 15]
4) M.prod(axis=1)  -> [  6 120]
5) np.cumsum(v)    -> [ 1  3  6 10]
```

In [8]:
M = np.array([[1, 2, 3],
              [4, 5, 6]])
v = np.array([1, 2, 3, 4])

np.sum(M)
np.sum(M, axis=0)
np.sum(M, axis=1)
np.prod(M, axis=1)

np.cumsum(v)

array([ 1,  3,  6, 10])

### Bài 8 — mean · std · var · median theo cột

**Yêu cầu:** Cho ma trận đặc trưng `X` (mỗi cột là 1 feature). Tính theo từng **cột** (`axis=0`): trung bình, độ lệch chuẩn (ddof=0), phương sai, trung vị.

**Input mẫu:**
```python
X = np.array([[ 2,  4],
              [ 6,  8],
              [10, 12]])
```

**Expected output:**
```
mean   -> [6. 8.]
std    -> [3.266 3.266]
var    -> [10.6667 10.6667]
median -> [6. 8.]
```

In [9]:
X = np.array([[ 2,  4],
              [ 6,  8],
              [10, 12]])

np.mean(X, axis=0)
np.std(X, axis=0)
np.var(X, axis=0)
np.median(X, axis=0)

array([6., 8.])

### Bài 9 — argmax / max theo trục (dự đoán lớp từ xác suất)

**Yêu cầu:** Cho ma trận xác suất `P` (mỗi hàng là phân phối xác suất trên 3 lớp của 1 mẫu).
1. Tìm **lớp dự đoán** của mỗi mẫu = chỉ số xác suất lớn nhất (`argmax`, `axis=1`).
2. Lấy **xác suất lớn nhất** của mỗi mẫu (`max`, `axis=1`).

**Input mẫu:**
```python
P = np.array([[0.1, 0.7, 0.2],
              [0.8, 0.1, 0.1],
              [0.3, 0.3, 0.4]])
```

**Expected output:**
```
1) np.argmax(P, axis=1) -> [1 0 2]
2) P.max(axis=1)        -> [0.7 0.8 0.4]
```

In [10]:
P = np.array([[0.1, 0.7, 0.2],
              [0.8, 0.1, 0.1],
              [0.3, 0.3, 0.4]])

np.argmax(P, axis=1)
np.max(P, axis=1)

array([0.7, 0.8, 0.4])

### Bài 10 — Chuẩn hóa tổng theo hàng = 1 (keepdims)

**Yêu cầu:** Cho ma trận `A`. Hãy chia mỗi hàng cho tổng của chính hàng đó để mỗi hàng cộng lại bằng 1 (gợi ý: `A.sum(axis=1, keepdims=True)`). In kết quả và tổng từng hàng sau khi chuẩn hóa.

**Input mẫu:**
```python
A = np.array([[1, 1, 2],
              [2, 3, 5]], dtype=float)
```

**Expected output:**
```
normalized ->
[[0.25 0.25 0.5 ]
 [0.2  0.3  0.5 ]]
row sums   -> [1. 1.]
```

In [11]:
A = np.array([[1, 1, 2],
              [2, 3, 5]], dtype=float)

A /= np.sum(A, axis=1, keepdims=True)
A


array([[0.25, 0.25, 0.5 ],
       [0.2 , 0.3 , 0.5 ]])

### Bài 11 — np.diff & đếm số lần tăng/giảm

**Yêu cầu:** Cho chuỗi `a`. Hãy:
1. Tính `np.diff(a)` (hiệu giữa các phần tử liền kề).
2. Đếm số lần chuỗi **tăng** (diff > 0) và số lần **giảm** (diff < 0).

**Input mẫu:**
```python
a = np.array([1, 3, 2, 2, 5, 4])
```

**Expected output:**
```
1) np.diff(a) -> [ 2 -1  0  3 -1]
2) số lần tăng -> 2 ; số lần giảm -> 2
```

In [12]:
a = np.array([1, 3, 2, 2, 5, 4])

_ = np.diff(a)
np.size(_[_ > 0]), np.size(_[_ < 0])

(2, 2)

## 🟨 Nhóm C — Reshape · Broadcasting · Vectorization

### Bài 12 — reshape · transpose · ravel · newaxis

**Yêu cầu:** Cho `a = np.arange(6)`. Hãy:
1. `reshape` thành ma trận 2×3.
2. Lấy chuyển vị của ma trận đó.
3. Trải phẳng lại về 1D (`ravel`).
4. In **shape** của `a[:, None]` (thêm 1 trục bằng `np.newaxis`).

**Input mẫu:**
```python
a = np.arange(6)
```

**Expected output:**
```
1) reshape(2,3) ->
[[0 1 2]
 [3 4 5]]
2) .T ->
[[0 3]
 [1 4]
 [2 5]]
3) ravel -> [0 1 2 3 4 5]
4) a[:, None].shape -> (6, 1)
```

In [13]:
a = np.arange(6)
a = a.reshape(2,3)
a.T
a.reshape(-1)
a[:,:,None].shape

(2, 3, 1)

### Bài 13 — Broadcasting: cộng vector vào hàng/cột

**Yêu cầu:** Cho ma trận `M`, vector hàng `v` và vector cột `c`. Hãy tính `M + v` (cộng vào từng hàng) và `M + c` (cộng vào từng cột) nhờ broadcasting.

**Input mẫu:**
```python
M = np.array([[1, 2, 3],
              [4, 5, 6]])
v = np.array([10, 20, 30])
c = np.array([[100],
              [200]])
```

**Expected output:**
```
M + v ->
[[11 22 33]
 [14 25 36]]
M + c ->
[[101 102 103]
 [204 205 206]]
```

In [14]:
M = np.array([[1, 2, 3],
              [4, 5, 6]])
v = np.array([10, 20, 30])
c = np.array([[100],
              [200]])

M + v
M + c

array([[101, 102, 103],
       [204, 205, 206]])

### Bài 14 — Vectorization: bảng cửu chương bằng broadcasting

**Yêu cầu:** Không dùng vòng lặp `for`, hãy tạo bảng nhân 4×4 trong đó phần tử `[i, j] = (i+1) * (j+1)` (gợi ý: nhân vector cột `[:, None]` với vector hàng `[None, :]`).

**Input mẫu:**
```python
n = 4  # tạo bảng nhân (n x n) từ np.arange(1, n+1)
```

**Expected output:**
```
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]
```

In [15]:
n = 4
col = np.arange(1, n + 1)
col = col.reshape(-1,1)
row = np.arange(1, n + 1)
row = row.reshape(1, -1)
# col[:, None] * row[None, :]
col * row

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16]])

### Bài 15 — stack · concatenate · split

**Yêu cầu:** Cho hai vector `a`, `b`. Hãy:
1. Ghép dọc `np.vstack`.
2. Ghép ngang `np.hstack`.
3. Ghép thành các cột với `np.stack(..., axis=1)`.
4. Chia `np.arange(6)` thành 3 phần bằng nhau với `np.split`.

**Input mẫu:**
```python
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
```

**Expected output:**
```
1) vstack ->
[[1 2 3]
 [4 5 6]]
2) hstack -> [1 2 3 4 5 6]
3) stack axis=1 ->
[[1 4]
 [2 5]
 [3 6]]
4) split -> [array([0, 1]), array([2, 3]), array([4, 5])]
```

In [16]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.vstack([a, b])
np.hstack([a,b])

np.stack([a, b], axis=1)

m = np.hstack((a,b))
np.split(m, 3)

[array([1, 2]), array([3, 4]), array([5, 6])]

### Bài 16 — sort · argsort · top-k

**Yêu cầu:** Cho mảng `a`. Hãy:
1. Sắp xếp tăng dần (`np.sort`).
2. Lấy chỉ số sắp xếp tăng dần (`np.argsort`).
3. Lấy 3 giá trị **lớn nhất** (giảm dần).
4. Lấy **chỉ số** của 3 giá trị lớn nhất (giảm dần).

**Input mẫu:**
```python
a = np.array([5, 2, 9, 1, 7, 3])
```

**Expected output:**
```
1) np.sort(a)    -> [1 2 3 5 7 9]
2) np.argsort(a) -> [3 1 5 0 4 2]
3) top-3 values  -> [9 7 5]
4) top-3 indices -> [2 4 0]
```

In [17]:
a = np.array([5, 2, 9, 1, 7, 3])
np.sort(a)
np.argsort(a)
np.sort(a)[-1:-4:-1]
np.argsort(a)[-1:-4:-1]

array([2, 4, 0])

## 🟧 Nhóm D — Đại số tuyến tính / Ma trận

### Bài 17 — Nhân ma trận @ vs nhân phần tử * ; dot

**Yêu cầu:** Cho ma trận `A`, `B` và vector `u`, `v`. Hãy tính:
1. Nhân **theo phần tử** `A * B`.
2. Nhân **ma trận** `A @ B`.
3. Tích vô hướng `np.dot(u, v)`.

**Input mẫu:**
```python
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])
u = np.array([1, 2, 3]); v = np.array([4, 5, 6])
```

**Expected output:**
```
1) A * B ->
[[ 5 12]
 [21 32]]
2) A @ B ->
[[19 22]
 [43 50]]
3) np.dot(u, v) -> 32
```

### Bài 18 — transpose · trace · diag

**Yêu cầu:** Cho ma trận `A`. Hãy tính: chuyển vị `A.T`, vết `np.trace(A)`, đường chéo chính `np.diag(A)`, và tạo ma trận đường chéo từ `[1, 2, 3]` bằng `np.diag`.

**Input mẫu:**
```python
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
```

**Expected output:**
```
A.T ->
[[1 4 7]
 [2 5 8]
 [3 6 9]]
trace -> 15
diag(A) -> [1 5 9]
diag([1,2,3]) ->
[[1 0 0]
 [0 2 0]
 [0 0 3]]
```

### Bài 19 — Định thức · ma trận nghịch đảo

**Yêu cầu:** Cho ma trận vuông `A`. Hãy tính định thức `np.linalg.det(A)`, ma trận nghịch đảo `np.linalg.inv(A)`, và kiểm tra `A @ A_inv` xấp xỉ ma trận đơn vị.

**Input mẫu:**
```python
A = np.array([[4., 7.],
              [2., 6.]])
```

**Expected output:**
```
det -> 10.0
inv ->
[[ 0.6 -0.7]
 [-0.2  0.4]]
A @ inv ->
[[1. 0.]
 [0. 1.]]
```

### Bài 20 — Giải hệ phương trình tuyến tính

**Yêu cầu:** Giải hệ:
```
2x +  y = 5
 x + 3y = 10
```
bằng `np.linalg.solve(A, b)` với `A` là ma trận hệ số, `b` là vế phải.

**Input mẫu:**
```python
A = np.array([[2., 1.],
              [1., 3.]])
b = np.array([5., 10.])
```

**Expected output:**
```
np.linalg.solve(A, b) -> [1. 3.]   # x = 1, y = 3
```

### Bài 21 — Hồi quy tuyến tính dạng đóng (normal equation)

**Yêu cầu:** Cho ma trận thiết kế `X` (cột đầu là bias = 1) và vector mục tiêu `y`. Hãy tính nghiệm bình phương tối thiểu theo công thức
`w = (Xᵀ X)⁻¹ Xᵀ y` (dữ liệu nằm trên đường thẳng `y = 1 + 2x`).

**Input mẫu:**
```python
X = np.array([[1., 0.],
              [1., 1.],
              [1., 2.],
              [1., 3.]])
y = np.array([1., 3., 5., 7.])
```

**Expected output:**
```
w -> [1. 2.]   # intercept = 1, slope = 2
```

## 🟥 Nhóm E — Metrics phân loại (Classification)

Các bài 22–25 dùng chung cặp nhãn nhị phân (lớp dương = 1) sau:
```python
y_true = np.array([1, 0, 1, 1, 0, 1, 0, 0, 1, 0])
y_pred = np.array([1, 0, 1, 0, 0, 1, 1, 0, 1, 1])
```

### Bài 22 — TP / FP / TN / FN (nhị phân)

**Yêu cầu:** Cho `y_true`, `y_pred` (lớp dương = 1). Hãy đếm bằng NumPy (không vòng lặp):
- **TP**: thật 1, dự đoán 1.
- **FP**: thật 0, dự đoán 1.
- **TN**: thật 0, dự đoán 0.
- **FN**: thật 1, dự đoán 0.

**Input mẫu:**
```python
y_true = np.array([1, 0, 1, 1, 0, 1, 0, 0, 1, 0])
y_pred = np.array([1, 0, 1, 0, 0, 1, 1, 0, 1, 1])
```

**Expected output:**
```
TP -> 4
FP -> 2
TN -> 3
FN -> 1
```

In [18]:
y_true = np.array([1, 0, 1, 1, 0, 1, 0, 0, 1, 0])
y_pred = np.array([1, 0, 1, 0, 0, 1, 1, 0, 1, 1])

tp = np.sum((y_true) & (y_pred))
tn = np.sum((y_true == 0) & (y_pred == 0))
fp = np.sum((y_true == 0) & (y_pred == 1))
fn = np.sum((y_true == 1) & (y_pred == 0))

tp, fp, tn, fn

(np.int64(4), np.int64(2), np.int64(3), np.int64(1))

### Bài 23 — Accuracy

**Yêu cầu:** Tính **accuracy** = số dự đoán đúng / tổng số mẫu (dùng cùng `y_true`, `y_pred` ở Bài 22).

**Input mẫu:**
```python
y_true = np.array([1, 0, 1, 1, 0, 1, 0, 0, 1, 0])
y_pred = np.array([1, 0, 1, 0, 0, 1, 1, 0, 1, 1])
```

**Expected output:**
```
accuracy -> 0.7
```

In [19]:
(tp + tn) / (tp + tn + fp + fn)

np.float64(0.7)

### Bài 24 — Precision & Recall

**Yêu cầu:** Từ TP, FP, FN (Bài 22), tính:
- **Precision** = TP / (TP + FP)
- **Recall**    = TP / (TP + FN)

**Input mẫu:**
```python
# TP = 4, FP = 2, FN = 1
```

**Expected output:**
```
precision -> 0.6667
recall    -> 0.8
```

In [20]:
precision = tp / (tp + fp)
recall = tp / (tp + fn)

precision, recall

(np.float64(0.6666666666666666), np.float64(0.8))

### Bài 25 — F1-score

**Yêu cầu:** Từ precision & recall (Bài 24), tính **F1** = 2·P·R / (P + R).

**Input mẫu:**
```python
# precision = 2/3, recall = 0.8
```

**Expected output:**
```
f1 -> 0.7273
```

In [21]:
f1 = 2 * precision * recall / (precision + recall)
f1

np.float64(0.7272727272727272)

### Bài 26 — Confusion matrix đa lớp (k×k) bằng NumPy thuần

**Yêu cầu:** Cho `y_true`, `y_pred` với 3 lớp (0, 1, 2). Hãy dựng ma trận nhầm lẫn `CM` kích thước 3×3, trong đó `CM[i, j]` = số mẫu **thật là lớp i** nhưng được **dự đoán là lớp j**. (Gợi ý: `np.add.at` hoặc cộng dồn theo cặp chỉ số.)

**Input mẫu:**
```python
y_true = np.array([0, 1, 2, 2, 0, 1, 1, 2, 0])
y_pred = np.array([0, 2, 2, 2, 0, 1, 0, 1, 0])
```

**Expected output:**
```
CM ->
[[3 0 0]
 [1 1 1]
 [0 1 2]]
```

In [22]:
y_true = np.array([0, 1, 2, 2, 0, 1, 1, 2, 0])
y_pred = np.array([0, 2, 2, 2, 0, 1, 0, 1, 0])

M = np.zeros((3,3))

np.add.at(M, (y_true, y_pred), 1)

M


array([[3., 0., 0.],
       [1., 1., 1.],
       [0., 1., 2.]])

### Bài 27 — Precision / Recall / F1 theo lớp + macro-average

**Yêu cầu:** Từ confusion matrix `CM` ở Bài 26, với mỗi lớp `c`: TP = `CM[c, c]`, FP = tổng cột c − TP, FN = tổng hàng c − TP. Hãy tính precision, recall, F1 cho **từng lớp**, rồi lấy trung bình (**macro-average**).

**Input mẫu:**
```python
CM = np.array([[3, 0, 0],
               [1, 1, 1],
               [0, 1, 2]])
```

**Expected output:**
```
precision theo lớp -> [0.75   0.5    0.6667]
recall    theo lớp -> [1.     0.3333 0.6667]
f1        theo lớp -> [0.8571 0.4    0.6667]
macro precision -> 0.6389
macro recall    -> 0.6667
macro f1        -> 0.6413
```

In [23]:
CM = np.array([[3, 0, 0],
               [1, 1, 1],
               [0, 1, 2]])
acc = sum([CM[i,i] for i in range(len(CM))]) / np.sum(CM)

tp = np.diag(CM)
fp = np.sum(CM, axis=0) - tp
fn = np.sum(CM, axis=1) - tp
tn = np.sum(CM) - tp - fp - fn
print(tp, fp, fn, tn)

precision = tp / (tp + fp)
recall = tp / (tp + fn)

f1 = 2 * precision * recall / (precision + recall)

print(precision, "\n", recall, "\n", f1)

macro_precision = np.mean(precision)
macro_recall = np.mean(recall)
macro_f1 = np.mean(f1)

macro_precision, macro_recall, macro_f1

[3 1 2] [1 1 1] [0 2 1] [5 5 5]
[0.75       0.5        0.66666667] 
 [1.         0.33333333 0.66666667] 
 [0.85714286 0.4        0.66666667]


(np.float64(0.6388888888888888),
 np.float64(0.6666666666666666),
 np.float64(0.6412698412698412))

### Bài 28 — Áp ngưỡng (threshold) lên xác suất → accuracy

**Yêu cầu:** Cho xác suất dự đoán `probs` và nhãn thật `y_true`. Với mỗi ngưỡng trong `[0.3, 0.5, 0.7]`, dự đoán nhãn = `(probs >= t)` rồi tính accuracy. In accuracy theo từng ngưỡng và chỉ ra ngưỡng tốt nhất.

**Input mẫu:**
```python
probs  = np.array([0.2, 0.8, 0.6, 0.4, 0.9, 0.35, 0.7, 0.1])
y_true = np.array([0,   1,   1,   0,   1,   0,    1,   0])
thresholds = [0.3, 0.5, 0.7]
```

**Expected output:**
```
t = 0.3 -> accuracy = 0.75
t = 0.5 -> accuracy = 1.0
t = 0.7 -> accuracy = 0.875
ngưỡng tốt nhất -> 0.5
```

In [24]:
probs  = np.array([0.2, 0.8, 0.6, 0.4, 0.9, 0.35, 0.7, 0.1])
y_true = np.array([0,   1,   1,   0,   1,   0,    1,   0])
thresholds = [0.3, 0.5, 0.7]

for threshold in thresholds:
  y_pred = np.where(probs >= threshold, 1, 0)
  tp = np.sum((y_pred) & (y_true))
  tn = np.sum((y_pred == 0) & (y_true == 0))
  acc = (tp + tn) / len(y_true)
  print(acc)


0.75
1.0
0.875


## 🟪 Nhóm F — Metrics hồi quy (Regression)

### Bài 29 — MAE & MSE

**Yêu cầu:** Cho giá trị thật `y_true` và dự đoán `y_pred`. Hãy tính:
- **MAE** = trung bình `|y_true − y_pred|`
- **MSE** = trung bình `(y_true − y_pred)²`

**Input mẫu:**
```python
y_true = np.array([3.0, 5.0, 2.5, 7.0])
y_pred = np.array([2.5, 5.0, 4.0, 6.0])
```

**Expected output:**
```
MAE -> 0.75
MSE -> 0.875
```

In [25]:
y_true = np.array([3.0, 5.0, 2.5, 7.0])
y_pred = np.array([2.5, 5.0, 4.0, 6.0])

mae = np.mean(np.abs(y_true - y_pred))
mse = np.mean((y_true - y_pred) ** 2)
mae, mse

(np.float64(0.75), np.float64(0.875))

### Bài 30 — RMSE

**Yêu cầu:** Tính **RMSE** = căn bậc hai của MSE (dùng cùng dữ liệu Bài 29).

**Input mẫu:**
```python
y_true = np.array([3.0, 5.0, 2.5, 7.0])
y_pred = np.array([2.5, 5.0, 4.0, 6.0])
```

**Expected output:**
```
RMSE -> 0.9354
```

In [26]:
y_true = np.array([3.0, 5.0, 2.5, 7.0])
y_pred = np.array([2.5, 5.0, 4.0, 6.0])

rmse = np.sqrt(np.mean((y_true - y_pred) ** 2))
rmse

np.float64(0.9354143466934853)

### Bài 31 — R² (hệ số xác định)

**Yêu cầu:** Tính **R²** = 1 − SS_res / SS_tot, với
`SS_res = Σ(y_true − y_pred)²` và `SS_tot = Σ(y_true − mean(y_true))²`.

**Input mẫu:**
```python
y_true = np.array([3, 5, 7, 9, 11])
y_pred = np.array([2.8, 5.1, 7.2, 8.9, 10.8])
```

**Expected output:**
```
R² -> 0.9965
```

In [27]:
y_true = np.array([3, 5, 7, 9, 11])
y_pred = np.array([2.8, 5.1, 7.2, 8.9, 10.8])

sse = np.sum((y_true - y_pred) ** 2)
tss = np.sum((y_true - np.mean(y_true)) ** 2)
r2 = 1 - sse / tss
r2

np.float64(0.9965)

## 🟫 Nhóm G — Preprocessing (Tiền xử lý đặc trưng)

### Bài 32 — Min-max scaling theo từng cột

**Yêu cầu:** Cho ma trận đặc trưng `X` (mỗi cột là 1 feature). Hãy đưa **mỗi cột** về đoạn `[0, 1]` theo công thức `(x − min) / (max − min)` (min/max tính theo cột).

**Input mẫu:**
```python
X = np.array([[1., 10.],
              [2., 20.],
              [3., 30.],
              [4., 40.]])
```

**Expected output:**
```
X_scaled ->
[[0.     0.    ]
 [0.3333 0.3333]
 [0.6667 0.6667]
 [1.     1.    ]]
```

In [28]:
X = np.array([[1., 10.],
              [2., 20.],
              [3., 30.],
              [4., 40.]])

X_scaled = (X - np.min(X, axis=0)) / (np.max(X, axis=0) - np.min(X, axis=0))
X_scaled

array([[0.        , 0.        ],
       [0.33333333, 0.33333333],
       [0.66666667, 0.66666667],
       [1.        , 1.        ]])

### Bài 33 — Standardize (z-score) theo từng cột

**Yêu cầu:** Chuẩn hóa **mỗi cột** của `X` về trung bình 0, độ lệch chuẩn 1 theo `z = (x − mean) / std` (mean & std tính theo cột, `ddof=0`).

**Input mẫu:**
```python
X = np.array([[1.,  2.],
              [3.,  6.],
              [5., 10.]])
```

**Expected output:**
```
X_z ->
[[-1.2247 -1.2247]
 [ 0.      0.    ]
 [ 1.2247  1.2247]]
```

In [29]:
X = np.array([[1.,  2.],
              [3.,  6.],
              [5., 10.]])

X_scaled = (X - np.mean(X, axis=0)) / np.std(X, axis=0)
X_scaled

array([[-1.22474487, -1.22474487],
       [ 0.        ,  0.        ],
       [ 1.22474487,  1.22474487]])

### Bài 34 — One-hot encoding

**Yêu cầu:** Cho vector nhãn nguyên `labels` (3 lớp: 0, 1, 2). Hãy tạo ma trận one-hot kích thước `(số mẫu, số lớp)` (gợi ý: `np.eye(num_classes)[labels]`).

**Input mẫu:**
```python
labels = np.array([0, 2, 1, 2, 0])
num_classes = 3
```

**Expected output:**
```
one_hot ->
[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
```

In [30]:
labels = np.array([0, 2, 1, 2, 0])
num_classes = 3

np.eye(3)[labels]

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

### Bài 35 — Centering: trừ mean theo cột (keepdims)

**Yêu cầu:** Cho ma trận `X`. Hãy trừ đi trung bình của **từng cột** để dữ liệu có mean = 0 theo cột (gợi ý: `X - X.mean(axis=0, keepdims=True)`). In kết quả và mean từng cột sau khi center.

**Input mẫu:**
```python
X = np.array([[1., 2., 3.],
              [4., 5., 6.],
              [7., 8., 9.]])
```

**Expected output:**
```
centered ->
[[-3. -3. -3.]
 [ 0.  0.  0.]
 [ 3.  3.  3.]]
mean theo cột sau center -> [0. 0. 0.]
```

In [31]:
X = np.array([[1., 2., 3.],
              [4., 5., 6.],
              [7., 8., 9.]])

X - np.mean(X, axis=0)

array([[-3., -3., -3.],
       [ 0.,  0.,  0.],
       [ 3.,  3.,  3.]])

## 🟦 Nhóm H — Distance & Similarity

### Bài 36 — Khoảng cách Euclidean & Manhattan

**Yêu cầu:** Cho hai vector `u`, `v`. Hãy tính:
- **Euclidean** = `sqrt(Σ (u − v)²)`
- **Manhattan** = `Σ |u − v|`

**Input mẫu:**
```python
u = np.array([1, 2, 3])
v = np.array([4, 6, 3])
```

**Expected output:**
```
euclidean -> 5.0
manhattan -> 7
```

In [32]:
u = np.array([1, 2, 3])
v = np.array([4, 6, 3])

euclidean = np.sqrt(np.sum((u - v) ** 2))
manhattan = np.sum(np.abs(u - v))
euclidean, manhattan

(np.float64(5.0), np.int64(7))

### Bài 37 — Cosine similarity

**Yêu cầu:** Cho hai vector `u`, `v`. Hãy tính độ tương đồng cosine = `dot(u, v) / (||u|| · ||v||)` (gợi ý: `np.linalg.norm`).

**Input mẫu:**
```python
u = np.array([1, 2, 2])
v = np.array([2, 3, 6])
```

**Expected output:**
```
cosine similarity -> 0.9524
```

In [33]:
u = np.array([1, 2, 2])
v = np.array([2, 3, 6])

cosine = np.dot(u, v) / (np.linalg.norm(u) * np.linalg.norm(v))
cosine

np.float64(0.9523809523809523)

### Bài 38 — Ma trận khoảng cách cặp (pairwise) bằng broadcasting

**Yêu cầu:** Cho tập điểm `P` (mỗi hàng là 1 điểm 2D). Hãy tính ma trận khoảng cách Euclidean cặp `D` với `D[i, j]` = khoảng cách giữa điểm i và điểm j (gợi ý: `P[:, None, :] - P[None, :, :]` rồi lấy norm theo trục cuối). Đây là bước lõi của thuật toán KNN.

**Input mẫu:**
```python
P = np.array([[0., 0.],
              [3., 0.],
              [0., 4.]])
```

**Expected output:**
```
D ->
[[0. 3. 4.]
 [3. 0. 5.]
 [4. 5. 0.]]
```

In [41]:
P = np.array([[0., 0.],
              [3., 0.],
              [0., 4.]])

np.linalg.norm(P[:, None, :] - P[None, :, :], axis=-1)

array([[0., 3., 4.],
       [3., 0., 5.],
       [4., 5., 0.]])