# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialise.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print(np.__version__)

2.0.2


#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
np.full(10, np.nan)

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
a = np.zeros(10)
np.size(a)

10

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
! python -c "import numpy as np; print(np.add.__doc__)"

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
a = np.full(10, np.nan)
a[4] = 1
a

array([nan, nan, nan, nan,  1., nan, nan, nan, nan, nan])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
a = np.arange(10,50)

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
a[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
a = np.arange(9)
a.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
t = np.array([1,2,0,0,4,0])
np.where(t == 0)

(array([2, 3, 5]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
np.random.randn(3,3,3)

array([[[ 1.1609007 , -0.89534826, -0.03349774],
        [-1.19151771, -0.24541493, -1.2801818 ],
        [-0.92612505,  0.02660627,  0.32360396]],

       [[ 0.00287566, -0.82380796, -1.52388066],
        [-2.27338267,  0.430442  , -0.45814777],
        [-1.47974854,  0.39508941, -0.45724603]],

       [[-1.07175214, -0.87283238,  0.53937163],
        [ 1.37479817,  0.41976222, -1.10132249],
        [-0.24462009, -0.30845345,  0.47266312]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:
a = np.random.rand(10,10)
np.min(a), np.max(a), a.min(), a.max()

(np.float64(0.003260215564059976),
 np.float64(0.996297259184914),
 np.float64(0.003260215564059976),
 np.float64(0.996297259184914))

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
a = np.random.rand(30)
a.mean(), np.mean(a)

(np.float64(0.5918209873504078), np.float64(0.5918209873504078))

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
a = np.zeros((5,5))
a[0] = 1; a[-1] = 1; a[:,0] = 1; a[:,-1] = 1
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
a = np.zeros((5,6))
row = np.ones((1, a.shape[1]))
col = np.ones((a.shape[0] + 2, 1))
row, col
a = np.concat((row, a, row), axis = 0)
a = np.concat((col, a, col), axis = 1)
a

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
3 * 0.1

0.30000000000000004

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:
np.diag([1,2,3,4], k = -1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
a = np.zeros((8,8))
a[::2, 1::2] = 1
a[1::2, ::2] = 1
a

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [ ]:
100 // (8 * 7), 100 % (8 * 7) // 8, 100 % (8 * 7) % 8

(1, 5, 4)

In [ ]:
np.unravel_index(100, (6,7,8))

(np.int64(1), np.int64(5), np.int64(4))

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
np.tile(np.array(([0,1],[1,0])), (4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [ ]:
np.random.randn(5,5)

array([[-0.71499819, -0.89576703,  0.14174674, -1.84576808, -0.12063652],
       [-2.11020464,  1.89611885,  0.06705985,  2.17979642,  0.99479531],
       [-0.37465703,  0.36501582, -0.73076669,  0.80514496, -1.3559176 ],
       [ 1.93741354, -0.27352423,  1.04221071,  0.59688157, -0.78632661],
       [-0.5611058 , -0.46087657, -0.8522011 , -0.37416993,  1.11338163]])

In [ ]:
a = np.random.rand(5,5)
(a - a.mean()) / a.std()

array([[ 0.13035023, -0.82795237, -1.05953596,  1.87063432,  0.76176117],
       [-0.239987  , -0.46171876, -1.12992063,  2.00179912, -1.23924726],
       [-0.5280119 , -0.63474865, -0.94247888, -0.10594955, -1.23570091],
       [ 0.58376301,  1.48011908,  1.60659004, -1.20731409,  0.81631869],
       [ 0.55629067,  0.86063735,  0.04576811, -0.575637  , -0.52582883]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
color = np.dtype([
    ('r', np.ubyte),
    ('g', np.ubyte),
    ('b', np.ubyte),
    ('a', np.ubyte),
])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
a = np.random.randint(low=0, high=10, size=(5,3))
b = np.random.randint(low=0, high=10, size=(3,2))
a @ b, np.dot(a, b), a.dot(b)

(array([[ 18,  20],
        [ 49,  14],
        [ 74,  36],
        [ 74,  36],
        [121,  94]]),
 array([[ 18,  20],
        [ 49,  14],
        [ 74,  36],
        [ 74,  36],
        [121,  94]]),
 array([[ 18,  20],
        [ 49,  14],
        [ 74,  36],
        [ 74,  36],
        [121,  94]]))

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
a = np.random.randint(low=0, high=10, size=10)
a[(a > 3) & (a < 8)] *= -1
a

array([ 3,  3,  8,  2, -7, -6, -7, -5,  9,  9])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
z = np.random.randint(low=0, high=5, size=5)
print(z)
print(z**z)
print(2 << z >> 2)
print(1 << (z-1))
print(z <- z)
print(1j*z)
print(z/1/1)
# print(z<z>z)

[4 0 0 4 4]
[256   1   1 256 256]
[8 0 0 8 8]
[8 0 0 8 8]
[False False False False False]
[0.+4.j 0.+0.j 0.+0.j 0.+4.j 0.+4.j]
[4. 0. 0. 4. 4.]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9223372036854775808]
[-9.22337204e+18]


/tmp/ipykernel_4041/2723105673.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
/tmp/ipykernel_4041/2723105673.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
/tmp/ipykernel_4041/2723105673.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int))
/tmp/ipykernel_4041/2723105673.py:4: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
a = np.random.uniform(-10, 10, 10)
print(a)
a = np.where(a > 0, np.ceil(a), np.floor(a))
print(a)

[ 3.29308876  4.3242225   5.22399805  4.47344454  6.92579426 -6.55713477
 -8.312672    6.95612064  0.63720604  5.62120702]
[ 4.  5.  6.  5.  7. -7. -9.  7.  1.  6.]


#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
np.intersect1d(np.random.randint(0,10,10), np.random.randint(0,10,10))

array([0, 1, 5, 7, 8, 9])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
import warnings
warnings.filterwarnings('ignore')

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
np.sqrt(-1), np.emath.sqrt(-1)

(np.float64(nan), np.complex128(1j))

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [ ]:
yesterday = np.datetime64('today') - np.timedelta64(1, 'D')
today     = np.datetime64('today')
tomorrow   = np.datetime64('today') + np.timedelta64(1, 'D')

print("Yesterday:", yesterday)
print("Today:    ", today)
print("Tomorrow: ", tomorrow)

Yesterday: 2026-06-11
Today:     2026-06-12
Tomorrow:  2026-06-13


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
np.arange("2016-07-01", "2016-07-31", dtype="datetime64[D]")

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
A = np.random.randint(0,10,(5,5))
B = np.random.randint(0,10,(5,5))

(A+B) @ (-A/2)

array([[-110.5, -152. ,  -78. , -142.5, -107.5],
       [-114.5, -149.5,  -71.5, -133. ,  -98.5],
       [ -61. ,  -53.5,  -37. ,  -69. ,  -58. ],
       [ -82. ,  -78. ,  -50.5, -118.5, -102. ],
       [ -92.5, -116.5,  -45.5, -134. , -104.5]])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [ ]:
a = np.random.uniform(-10, 10, 10)
print(a)
print(np.floor(a[a>0]))
print(a[a>0] // 1)
print(np.floor(a[np.where(a>0)]))
b = np.where(a>0, np.floor(a), np.nan)
print(b[~np.isnan(b)])

[ 4.16818373  6.91509743 -6.74130746  6.70972655  8.49446963 -5.52136487
 -4.15878065 -7.91455897 -7.50094163  3.71706534]
[4. 6. 6. 8. 3.]
[4. 6. 6. 8. 3.]
[4. 6. 6. 8. 3.]
[4. 6. 6. 8. 3.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
np.tile(np.array(np.arange(5)), (5,1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [ ]:
np.random.randint(-10, 10, 10)

array([ -2,   3,  -7,   3,   7,   4,   5,  -9, -10,  -2])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [ ]:
np.linspace(0, 1, 12)[1:-1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
np.sort(np.random.rand(10))

array([0.06665627, 0.13347241, 0.15608102, 0.26270405, 0.28464146,
       0.33532694, 0.578446  , 0.63554853, 0.68349959, 0.80469262])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [ ]:
a = np.random.rand(10)

%timeit np.sum(a)

%timeit np.add.reduce(a)

4.8 µs ± 2.08 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)
2.55 µs ± 1 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

In [ ]:
a = np.random.randint(0, 4, 10)
b = np.random.randint(0, 4, 10)

False not in (np.sort(a) == np.sort(b))

False

In [ ]:
np.array_equal(a, b)

False

#### 43. Make an array immutable (read-only) (★★☆)

In [ ]:
a = np.random.randint(0, 4, 10)
a.flags.writeable = False

try:
  a[0] = 99
except ValueError as e:
  print(f"Hey, {e}")

Hey, assignment destination is read-only


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [ ]:
cc = np.random.randint(-10, 10, (10, 2))
print(cc)

r = np.sqrt(np.sum(cc ** 2, axis = 1, keepdims=True))
theta = np.arctan2(cc[:, 0], cc[:, 1]).reshape(-1,1)

res = np.column_stack([r, theta])
print(res)

[[  9   0]
 [  1 -10]
 [  8   3]
 [  7   8]
 [  3   5]
 [  6   7]
 [ -8   7]
 [ -8  -5]
 [ -6   1]
 [ -7  -7]]
[[ 9.          1.57079633]
 [10.04987562  3.041924  ]
 [ 8.54400375  1.21202566]
 [10.63014581  0.71883   ]
 [ 5.83095189  0.5404195 ]
 [ 9.21954446  0.70862627]
 [10.63014581 -0.85196633]
 [ 9.43398113 -2.12939564]
 [ 6.08276253 -1.40564765]
 [ 9.89949494 -2.35619449]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [ ]:
a = np.random.rand(10)
a[a == a.max()] = 0
a

array([0.61379266, 0.06356125, 0.65566837, 0.17848436, 0.59584427,
       0.54501057, 0.71431937, 0.13859276, 0.04003716, 0.        ])

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [ ]:
x = np.tile(np.linspace(0, 1, 11), (11, 1))
y = x.T

res = np.stack((y, x), axis = 2)
res

array([[[0. , 0. ],
        [0. , 0.1],
        [0. , 0.2],
        [0. , 0.3],
        [0. , 0.4],
        [0. , 0.5],
        [0. , 0.6],
        [0. , 0.7],
        [0. , 0.8],
        [0. , 0.9],
        [0. , 1. ]],

       [[0.1, 0. ],
        [0.1, 0.1],
        [0.1, 0.2],
        [0.1, 0.3],
        [0.1, 0.4],
        [0.1, 0.5],
        [0.1, 0.6],
        [0.1, 0.7],
        [0.1, 0.8],
        [0.1, 0.9],
        [0.1, 1. ]],

       [[0.2, 0. ],
        [0.2, 0.1],
        [0.2, 0.2],
        [0.2, 0.3],
        [0.2, 0.4],
        [0.2, 0.5],
        [0.2, 0.6],
        [0.2, 0.7],
        [0.2, 0.8],
        [0.2, 0.9],
        [0.2, 1. ]],

       [[0.3, 0. ],
        [0.3, 0.1],
        [0.3, 0.2],
        [0.3, 0.3],
        [0.3, 0.4],
        [0.3, 0.5],
        [0.3, 0.6],
        [0.3, 0.7],
        [0.3, 0.8],
        [0.3, 0.9],
        [0.3, 1. ]],

       [[0.4, 0. ],
        [0.4, 0.1],
        [0.4, 0.2],
        [0.4, 0.3],
        [0.4, 0.4],
        [0.4

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [ ]:
x = np.random.randint(0, 10, 10)
y = np.random.randint(0, 10, 10)

xx = np.tile(x, (x.shape[0], 1))
yy = np.tile(-y, (y.shape[0], 1)).T

mat = np.stack([xx, yy], axis = -1)
1 / np.sum(mat, axis = 2)

array([[ 0.33333333,  1.        ,         inf, -1.        ,  0.2       ,
         0.14285714,  0.33333333,  0.5       ,  0.33333333,  0.16666667],
       [        inf, -0.5       , -0.33333333, -0.25      ,  0.5       ,
         0.25      ,         inf, -1.        ,         inf,  0.33333333],
       [ 0.5       ,         inf, -1.        , -0.5       ,  0.25      ,
         0.16666667,  0.5       ,  1.        ,  0.5       ,  0.2       ],
       [-0.33333333, -0.2       , -0.16666667, -0.14285714, -1.        ,
         1.        , -0.33333333, -0.25      , -0.33333333,         inf],
       [-0.2       , -0.14285714, -0.125     , -0.11111111, -0.33333333,
        -1.        , -0.2       , -0.16666667, -0.2       , -0.5       ],
       [ 1.        , -1.        , -0.5       , -0.33333333,  0.33333333,
         0.2       ,  1.        ,         inf,  1.        ,  0.25      ],
       [-1.        , -0.33333333, -0.25      , -0.2       ,  1.        ,
         0.33333333, -1.        , -0.5       

In [ ]:
1 / (x.reshape(-1,1) - y.reshape(1,-1))

array([[ 0.33333333,         inf,  0.5       , -0.33333333, -0.2       ,
         1.        , -1.        ,  0.25      ,  0.5       ,  1.        ],
       [ 1.        , -0.5       ,         inf, -0.2       , -0.14285714,
        -1.        , -0.33333333,  0.5       ,         inf, -1.        ],
       [        inf, -0.33333333, -1.        , -0.16666667, -0.125     ,
        -0.5       , -0.25      ,  1.        , -1.        , -0.5       ],
       [-1.        , -0.25      , -0.5       , -0.14285714, -0.11111111,
        -0.33333333, -0.2       ,         inf, -0.5       , -0.33333333],
       [ 0.2       ,  0.5       ,  0.25      , -1.        , -0.33333333,
         0.33333333,  1.        ,  0.16666667,  0.25      ,  0.33333333],
       [ 0.14285714,  0.25      ,  0.16666667,  1.        , -1.        ,
         0.2       ,  0.33333333,  0.125     ,  0.16666667,  0.2       ],
       [ 0.33333333,         inf,  0.5       , -0.33333333, -0.2       ,
         1.        , -1.        ,  0.25      

#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

In [ ]:
np.iinfo(np.int8)

iinfo(min=-128, max=127, dtype=int8)

#### 49. How to print all the values of an array? (★★☆)

In [ ]:
print(a)

[0.61379266 0.06356125 0.65566837 0.17848436 0.59584427 0.54501057
 0.71431937 0.13859276 0.04003716 0.        ]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [ ]:
target = 0.5
a[np.argmin(abs(a - target))]

np.float64(0.5450105712866289)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [ ]:
np.dtype([
    ('r', np.uint8),
    ('g', np.uint8),
    ('b', np.uint8),
])

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1')])

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [ ]:
a = np.random.randint(0, 180, (100, 2))
np.sqrt(np.sum(a ** 2, axis = 1))

array([110.94142599, 168.40427548, 144.01388822, 191.38442988,
       124.61540836, 205.80087463,  89.27485648, 146.10954794,
       104.12012294,  41.18252056,  61.84658438, 195.2331939 ,
       174.10341754, 222.08106628, 127.94530081, 141.35416513,
       141.90489773, 188.95766722, 133.33041663, 180.00555547,
       136.41847382,  72.12489168, 214.33618453, 158.52129195,
       201.40506448, 112.05802069, 114.48143954,  71.47027354,
       150.1632445 , 183.29484444, 215.67800073, 160.32778923,
        89.27485648, 133.76471882, 160.55528643, 145.90750495,
        84.05355436, 202.20039565, 239.71858501, 111.00450441,
       181.95878654, 127.12985487, 179.25400972, 116.84605256,
       147.86818454,  72.56721023, 148.83883902, 135.2479205 ,
       116.60617479, 137.18600512,  95.75489544,  78.54934755,
       140.7302384 , 183.4039258 ,  78.40918314, 177.72169254,
       140.35668848,  48.33218389, 132.23085873, 157.63248396,
       189.77091453, 218.24756585, 114.05700329, 162.41

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

In [ ]:
a = np.array([1,2,3,43.2], dtype=np.float16)
a.astype(np.int16)

array([ 1,  2,  3, 43], dtype=int16)

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO

s = StringIO('''1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11''')

Z = np.genfromtxt(s, delimiter=",", dtype=np.float64)
print(Z)

[[ 1.  2.  3.  4.  5.]
 [ 6. nan nan  7.  8.]
 [nan nan  9. 10. 11.]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [ ]:
a = np.random.rand(10, 2)
print(a)
for index, value in np.ndenumerate(a):
  print(f"Index: {index}: value {value}")

[[0.16451039 0.58630627]
 [0.19411417 0.08358578]
 [0.81220567 0.32890578]
 [0.81538634 0.06052612]
 [0.837361   0.30230625]
 [0.10221522 0.70708272]
 [0.28233158 0.97922299]
 [0.03354864 0.14656108]
 [0.25404466 0.08064517]
 [0.47656483 0.35648713]]
Index: (0, 0): value 0.16451038616691116
Index: (0, 1): value 0.5863062655833194
Index: (1, 0): value 0.19411416996531716
Index: (1, 1): value 0.08358578475888045
Index: (2, 0): value 0.8122056690412084
Index: (2, 1): value 0.32890578405730464
Index: (3, 0): value 0.8153863396677827
Index: (3, 1): value 0.06052612234482868
Index: (4, 0): value 0.8373609989806752
Index: (4, 1): value 0.30230625263159083
Index: (5, 0): value 0.10221522466590327
Index: (5, 1): value 0.7070827167590094
Index: (6, 0): value 0.28233158288825855
Index: (6, 1): value 0.9792229863715992
Index: (7, 0): value 0.033548641454503314
Index: (7, 1): value 0.14656108309144056
Index: (8, 0): value 0.2540446565905422
Index: (8, 1): value 0.08064516569617641
Index: (9, 0): va

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [ ]:
x, y = np.meshgrid(np.linspace(-1, 1, 10), np.linspace(-1, 1, 10))
sigma = 1.0
exp(- (x ** 2 + y ** 2) / (2 * sigma ** 2)) / (2 * np.pi * sigma ** 2)

array([[0.05854983, 0.07133657, 0.08272793, 0.09131569, 0.09593831,
        0.09593831, 0.09131569, 0.08272793, 0.07133657, 0.05854983],
       [0.07133657, 0.08691581, 0.10079493, 0.11125819, 0.11689034,
        0.11689034, 0.11125819, 0.10079493, 0.08691581, 0.07133657],
       [0.08272793, 0.10079493, 0.11689034, 0.12902442, 0.13555594,
        0.13555594, 0.12902442, 0.11689034, 0.10079493, 0.08272793],
       [0.09131569, 0.11125819, 0.12902442, 0.1424181 , 0.14962764,
        0.14962764, 0.1424181 , 0.12902442, 0.11125819, 0.09131569],
       [0.09593831, 0.11689034, 0.13555594, 0.14962764, 0.15720215,
        0.15720215, 0.14962764, 0.13555594, 0.11689034, 0.09593831],
       [0.09593831, 0.11689034, 0.13555594, 0.14962764, 0.15720215,
        0.15720215, 0.14962764, 0.13555594, 0.11689034, 0.09593831],
       [0.09131569, 0.11125819, 0.12902442, 0.1424181 , 0.14962764,
        0.14962764, 0.1424181 , 0.12902442, 0.11125819, 0.09131569],
       [0.08272793, 0.10079493, 0.1168903

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [ ]:
p = 5
x = np.full(p, 1410)
idx = np.random.randint(0, a.shape[0] * a.shape[1], p)
a = np.random.rand(10,2)


#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)